# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgis/postgis:13-3.0
    restart: always
    environment:
      POSTGRES_DB: food-delivery
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432